version: '2'
services:
  drupal:
    image: drupal:8.1.1-apache
    ports:
      - 80
    links:
      - mysql
    volumes:
      - ./cambridge:/var/www/html/themes/cambridge
      - site:/var/www/html/

    ports:
      - 8080:80
  mysql:
    image: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
  drush:
    image: drush/drush:9
    volumes:
      - site:/app
volumes:
  site: {}
